# Generated by Django 3.0 on 2020-10-14 04:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('SKU', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_description', models.TextField()),
                ('product_category', models.CharField(max_length=100)),
                ('product_stock', models.IntegerField()),
                ('product_location', models.CharField(max_length=50)),
                ('product_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
