# Generated by Django 3.0 on 2020-11-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0003_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'products'},
        ),
    ]
