# Generated by Django 3.0 on 2020-11-18 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0004_auto_20201112_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customers'},
        ),
    ]
