# Generated by Django 3.0 on 2020-11-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0006_auto_20201118_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
