# Generated by Django 3.0 on 2020-11-20 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman', '0008_auto_20201119_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='Products'),
        ),
    ]
